#!/bin/bash
# Use this script to restart gpg, which will clear the cache
# of all entered passphrases, among other things.
# (Note: This will just stop gpg, and it will start back up automatically when needed)

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

gpgconf --kill gpg-agent
"$SCRIPT_DIR"/ClearClipboard
